resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=302d095

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=302d095

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENVIRONMENT=dev
      - DD_VERSION=302d095

images:
  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-api
    newTag: "302d095"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "302d095"

  - name: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-image-api
    newTag: "302d095"
